"""empty message

Revision ID: 11045487b016
Revises: 5d84824d4854
Create Date: 2025-09-17 18:15:05.235892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11045487b016'
down_revision = '5d84824d4854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=240), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
