"""empty message

Revision ID: 69e9ab5a73a7
Revises: 11045487b016
Create Date: 2025-09-17 18:16:31.226355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e9ab5a73a7'
down_revision = '11045487b016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=240), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=240), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
